---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-22
    image: geerlingguy/docker-ubuntu2204-ansible@sha256:48a18d65f05ddbf00456c3ac463a00b78f32137d351a35ee9ce90051f440d375
    command: /sbin/init
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: ubuntu-24
    image: geerlingguy/docker-ubuntu2404-ansible@sha256:8f71d6ef6617ce600a0c9f210a21bff095ef9cf2b7c5ac437f838e697ad5bbe5
    command: /sbin/init
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: rocky-9
    image: geerlingguy/docker-rockylinux9-ansible@sha256:5b5b69fcad35dec33d41faf6432d7c25cebc1979b4d566c26fa1c05fd3ccebe1
    command: /sbin/init
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/../
  inventory:
    host_vars:
      ubuntu-22:
        ansible_python_interpreter: /usr/bin/python3
        wordpress_php_version: "8.1"
      ubuntu-24:
        ansible_python_interpreter: /usr/bin/python3
        wordpress_php_version: "8.3"
      rocky-9:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    prepare: prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: verify.yml
  lint:
    name: ansible-lint
    enabled: false  # Already done in CI

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
