---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for container command execution
      ansible.builtin.raw: /bin/true
      register: container_ready
      changed_when: false
      retries: 30
      delay: 2
      until: container_ready.rc == 0

    - name: Install python for Ansible
      ansible.builtin.raw: test -e /usr/bin/python3 || (dnf -y install python3)
      changed_when: false
      failed_when: false
