---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: debian-11
    image: geerlingguy/docker-debian11-ansible@sha256:f32d1ab35477ff4b2b46f82097ae955d6ea1e71c41eb146ba1df150c850d859e
    command: /sbin/init
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: debian-12
    image: geerlingguy/docker-debian12-ansible@sha256:2effe5239c105630a302ec605f5d7df9e72a8894a0186a8dcec824d366abbff1
    command: /sbin/init
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/../
  inventory:
    host_vars:
      debian-11:
        ansible_python_interpreter: /usr/bin/python3
        wordpress_php_version: "7.4"
      debian-12:
        ansible_python_interpreter: /usr/bin/python3
        wordpress_php_version: "8.2"
  playbooks:
    prepare: prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: verify.yml
  lint:
    name: ansible-lint
    enabled: false  # Already done in CI

verifier:
  name: ansible

scenario:
  name: debian
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
